#create a table in psql
dwh_dl_facebook_post_insights = ''' create table dwh_dl_facebook_post_insights(
       insights_created_date text,
       post_activity varchar(64) NOT NULL,
       post_activity_by_action_type json,
       post_activity_by_action_type_unique text,
       post_activity_unique varchar(64) NOT NULL,
       post_clicks varchar(64) NOT NULL,
       post_clicks_by_type text,
       post_clicks_by_type_unique text,
       post_clicks_unique varchar(64) NOT NULL,
       post_engaged_fan varchar(64) NOT NULL,
       post_engaged_users varchar(64) NOT NULL,
       post_id varchar(64) NOT NULL,
       post_impressions varchar(64) NOT NULL,
       post_impressions_by_story_type text,
       post_impressions_by_story_type_unique text,
       post_impressions_fan varchar(64) NOT NULL,
       post_impressions_fan_paid varchar(64) NOT NULL,
       post_impressions_fan_paid_unique varchar(64) NOT NULL,
       post_impressions_fan_unique varchar(64) NOT NULL,
       post_impressions_nonviral varchar(64) NOT NULL,
       post_impressions_nonviral_unique varchar(64) NOT NULL,
       post_impressions_organic varchar(64) NOT NULL,
       post_impressions_organic_unique varchar(64) NOT NULL,
       post_impressions_paid varchar(64) NOT NULL,
       post_impressions_paid_unique varchar(64) NOT NULL,
       post_impressions_unique varchar(64) NOT NULL,
       post_impressions_viral varchar(64) NOT NULL,
       post_impressions_viral_unique varchar(64) NOT NULL,
       post_negative_feedback varchar(64) NOT NULL,
       post_negative_feedback_by_type text,
       post_negative_feedback_by_type_unique text,
       post_negative_feedback_unique varchar(64) NOT NULL,
       post_reactions_anger_total varchar(64) NOT NULL,
       post_reactions_by_type_total text,
       post_reactions_haha_total varchar(64),
       post_reactions_like_total varchar(64),
       post_reactions_love_total varchar(64),
       post_reactions_sorry_total varchar(64),
       post_reactions_wow_total varchar(64),
       post_video_avg_time_watched varchar(64),
       post_video_complete_views_organic varchar(64),
       post_video_complete_views_organic_unique varchar(64),
       post_video_complete_views_paid varchar(64),
       post_video_complete_views_paid_unique varchar(64),
       post_video_length varchar(64),
       post_video_retention_graph text,
       post_video_retention_graph_autoplayed text,
       post_video_retention_graph_clicked_to_play text,
       post_video_view_time text,
       post_video_view_time_by_age_bucket_and_gender json,
       post_video_view_time_by_country_id text,
       post_video_view_time_by_distribution_type text,
       post_video_view_time_by_region_id text,
       post_video_view_time_organic varchar(64),
       post_video_views varchar(64),
       post_video_views_10s varchar(64),
       post_video_views_10s_autoplayed varchar(64),
       post_video_views_10s_clicked_to_play varchar(64),
       post_video_views_10s_organic varchar(64),
       post_video_views_10s_paid varchar(64),
       post_video_views_10s_sound_on varchar(64),
       post_video_views_10s_unique varchar(64),
       post_video_views_autoplayed varchar(64),
       post_video_views_by_distribution_type text,
       post_video_views_clicked_to_play varchar(64),
       post_video_views_organic varchar(64),
       post_video_views_organic_unique varchar(64),
       post_video_views_paid varchar(64),
       post_video_views_paid_unique varchar(64),
       post_video_views_sound_on varchar(64),
       post_video_views_unique varchar(64),
       period varchar(64));'''

#copy the csv data into the table we created with separation of delimiter
copy_sql = """
           COPY dwh_dl_facebook_post_insights FROM stdin WITH CSV HEADER
           DELIMITER as ','
           """

#extracting the json column and creating a new table from it
postgender = ''' create table postgender AS ( SELECT post_id,
                   cast(post_video_view_time_by_age_bucket_and_gender ->> 'U.18-24' AS numeric) AS U18t24,
                   cast(post_video_view_time_by_age_bucket_and_gender ->> 'U.25-34' AS numeric) AS U25t34,
                   cast(post_video_view_time_by_age_bucket_and_gender ->> 'U.35-44' AS numeric) AS U35t44,
                   cast(post_video_view_time_by_age_bucket_and_gender ->> 'U.45-54' AS numeric) AS U45t54,
                   cast(post_video_view_time_by_age_bucket_and_gender ->> 'U.55-64' AS numeric) AS U55t64,
                   cast(post_video_view_time_by_age_bucket_and_gender ->> 'U.65+' AS numeric) AS U65plus,
                   cast(post_video_view_time_by_age_bucket_and_gender ->> 'F.13-17' AS numeric) AS f13t17,
                   cast(post_video_view_time_by_age_bucket_and_gender ->> 'F.18-24' AS numeric) AS f18t24,
                   cast(post_video_view_time_by_age_bucket_and_gender ->> 'F.25-34' AS numeric) AS f25t34,
                   cast(post_video_view_time_by_age_bucket_and_gender ->> 'F.35-44' AS numeric) AS f35t44,
                   cast(post_video_view_time_by_age_bucket_and_gender ->> 'F.45-54' AS numeric) AS f45t54,
                   cast(post_video_view_time_by_age_bucket_and_gender ->> 'F.55-64'  AS numeric) AS f55t64,
                   cast(post_video_view_time_by_age_bucket_and_gender ->> 'F.65+' AS numeric)  AS f65plus,
                   cast(post_video_view_time_by_age_bucket_and_gender ->> 'M.13-17' AS numeric) AS M13t17,
                   cast(post_video_view_time_by_age_bucket_and_gender ->> 'M.18-24' AS numeric) AS M18t24,
                   cast(post_video_view_time_by_age_bucket_and_gender ->> 'M.25-34' AS numeric) AS M25t34,
                   cast(post_video_view_time_by_age_bucket_and_gender ->> 'M.35-44' AS numeric) AS M35t44,
                   cast(post_video_view_time_by_age_bucket_and_gender ->> 'M.45-54' AS numeric) AS M45t54,
                   cast(post_video_view_time_by_age_bucket_and_gender ->> 'M.55-64' AS numeric) AS M55t64,
                   cast(post_video_view_time_by_age_bucket_and_gender ->> 'M.65+' AS numeric) AS M65plus
                   FROM dwh_dl_facebook_post_insights);
              '''

#query for sums per post for each gender and age 18-34 of all genders.
post_for_each_gender = ''' select post_id,sum(f18t24+f25t34+m18t24+m25t34+u18t24+u25t34) AS age,
                           sum(f13t17+f18t24+f25t34+f35t44+f45t54+f55t64+f65plus) as Female,
                           sum(m13t17+m18t24+m25t34+m35t44+m45t54+m55t64+m65plus) as Male,
                           sum(u18t24+u25t34+u35t44+u45t54+u55t64+u65plus) as Unknown from postgender 
                           where post_id in ('1804124663153407_1961448124087726','1804124663153407_1952050305027508','1804124663153407_1950421771857028') 
                           group by post_id order by Unknown asc;
                       '''